### ISSUE TITLE
RuleFilterParser handle int values in the filter

### ISSUE THREAD

**Issue by MarioCzyz** [bcc-code/rule-filter-parser-dotnet#18]
int, long, double values are always parsed as double, in the result it makes type mismatch with db entities. 

Example RegistrationHours endpoint in Contribution API

Sending { "registrationId":{"_eq": 333755}}  in the filter returns error because registrationId is type nullable Int32 but this value provided in the filter is always parsed to double

**Comment by piotrczyz** [comment]
Can you try using data types with suffixes:
```csharp
decimal a = 2.1m; // { "a":{"_eq": 2.1m}}
double b = 2.1d; // { "b":{"_eq": 2.1d}}
int c = 42; // { "c":{"_eq": 42}}
...
```

https://www.c-sharpcorner.com/article/data-type-suffixes-in-c-sharp/
https://www.tutorialsteacher.com/csharp/csharp-data-types
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types

**Comment by MarioCzyz** [comment]
Accordingly to passing tests in the parser, more rules should work "out of the box" but are not working 

![image](https://github.com/bcc-code/rule-filter-parser-dotnet/assets/84964131/2b9555e2-da0e-4806-9705-3f47bc3f5ba0)

![image](https://github.com/bcc-code/rule-filter-parser-dotnet/assets/84964131/eae59406-01af-4f0a-9406-002b8a6864e2)

**Comment by piotrczyz** [comment]
> Can you try using data types with suffixes:
> 
> ```cs
> decimal a = 2.1m; // { "a":{"_eq": 2.1m}}
> double b = 2.1d; // { "b":{"_eq": 2.1d}}
> int c = 42; // { "c":{"_eq": 42}}
> ...
> ```
> 
> https://www.c-sharpcorner.com/article/data-type-suffixes-in-c-sharp/ https://www.tutorialsteacher.com/csharp/csharp-data-types https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types

Second thoughts, we can't use that because it will put restrictions on API. We would need to use reflection to find out the types.
