### ISSUE TITLE
Rename library to `BccCode.Linq`

### ISSUE THREAD

**Issue by leo-schick** [bcc-code/rule-filter-parser-dotnet#31]
Reng and @leo-schick  had a chat about the library name and we decided that it shall be changed to `BccCode.Linq`.

**Comment by leo-schick** [comment]
@piotrczyz

**Comment by u12206050** [comment]
Doesn't really tell you what it does though. It is too generic in my opinion

**Comment by leo-schick** [comment]
@u12206050 I had the same idea but came with Reng to the conclution that this would make more sence. What name would you suggest?

The current main functions these library offers are:

- providing [`ApplyRuleFilter`](https://github.com/bcc-code/rule-filter-parser-dotnet/blob/main/src/RuleFilterParser/Extensions/CollectionsExtensions.cs#L5-L15) extension methods which are used on server side to cast a `jsonFilter` string into a (Linq) Expression tree. (-> which is then passed over to EF Core which converts it into SQL ...)
- providing class `ApiQueryable`, a class which supports IQueryable<T> and parses Linq expressions into an API request.
- providing class `ApiPagedEnumerable` which performs the actual API requests.
The API client must implement interface `IApiClient` which performs the actual endpoint operations like `Get(endpoint, request)` and `GetAsync(endpoint, request, cancellationToken)`

So, mainly it implements Linq/Query logic on server and client side of an API in the [Directus](https://docs.directus.io/reference/query.html) API style (we just don't call it like that)

**Comment by u12206050** [comment]
Hmm isn't it missing the validate payload functionality as well? 
It basically compared the query given to a given payload / state to validate it.

But based on whatvit already has what about LINQueryParser?

**Comment by leo-schick** [comment]
@u12206050 Actually, I do not see any validation logic here. It throws errors, yes, but only when you do something which is not supported.

**Comment by leo-schick** [comment]
I had a chat with Reng and we decided to keep the name. PR for this see #35 ready to be merged.
